name: proxmox_controller
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  dart_frog: ^0.3.0
  dart_ping: ^8.0.1
  dartssh2: ^2.8.2
  dotenv: ^4.1.0
  equatable: ^2.0.5
  network_tools: ^3.2.1

dev_dependencies:
  build_runner: ^2.4.6
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0

assets:
  - .env